/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package my.board;
import my.Game;
/**
 *
 * @author Justin
 */
public class Board_jFrame extends javax.swing.JFrame
{

    /**
     * Creates new form Board
     */
    public Board_jFrame()
    {
        initComponents();
        Board.spaces.add( new Space("Go",jButton_Go.getX(),jButton_Go.getY()));
        Board.spaces.add( new Space("Flying Fortress",jButton_Purple1.getX(),jButton_Purple1.getY()));
        Board.spaces.add( new Space("Community Chest",jButton_Chest1.getX(),jButton_Chest1.getY()));
        Board.spaces.add( new Space("Pandemonium",jButton_Purple2.getX(),jButton_Purple2.getY()));
        Board.spaces.add( new Space("Income Tax",jButton_Tax_Income.getX(),jButton_Tax_Income.getY()));
        Board.spaces.add( new Space("*Rail1*",jButton_Rail1.getX(),jButton_Rail1.getY()));
        Board.spaces.add( new Space("Floating Continent",jButton_Teal1.getX(),jButton_Teal1.getY()));
        Board.spaces.add( new Space("Chance",jButton_Chance1.getX(),jButton_Chance1.getY()));
        Board.spaces.add( new Space("Crystal Tower",jButton_Teal2.getX(),jButton_Teal2.getY()));
        Board.spaces.add( new Space("Baron",jButton_Teal3.getX(),jButton_Teal3.getY()));
        Board.spaces.add( new Space("Jail",jButton_Jail.getX(),jButton_Jail.getY()));
        Board.spaces.add( new Space("Ancient's Library",jButton_Pink1.getX(),jButton_Pink1.getY()));
        Board.spaces.add( new Space("Electric Company",jButton_Utility_Electric.getX(),jButton_Utility_Electric.getY()));
        Board.spaces.add( new Space("Exdeath's Castle",jButton_Pink2.getX(),jButton_Pink2.getY()));
        Board.spaces.add( new Space("Castle Kuza",jButton_Pink3.getX(),jButton_Pink3.getY()));
        Board.spaces.add( new Space("*Rail2*",jButton_Rail2.getX(),jButton_Rail2.getY()));
        Board.spaces.add( new Space("Figaro Castle",jButton_Orange1.getX(),jButton_Orange1.getY()));
        Board.spaces.add( new Space("Community Chest",jButton_Chest2.getX(),jButton_Chest2.getY()));
        Board.spaces.add( new Space("Imperial Palace",jButton_Orange2.getX(),jButton_Orange2.getY()));
        Board.spaces.add( new Space("Kefka's Tower",jButton_Orange3.getX(),jButton_Orange3.getY()));
        Board.spaces.add( new Space("Free Parking",jButton_FreeParking.getX(),jButton_FreeParking.getY()));
        Board.spaces.add( new Space("Golden Saucer",jButton_Red1.getX(),jButton_Red1.getY()));
        Board.spaces.add( new Space("Chance",jButton_Chance2.getX(),jButton_Chance2.getY()));
        Board.spaces.add( new Space("Junon",jButton_Red2.getX(),jButton_Red2.getY()));
        Board.spaces.add( new Space("Midgar",jButton_Red3.getX(),jButton_Red3.getY()));
        Board.spaces.add( new Space("*Rail3*",jButton_Rail3.getX(),jButton_Rail3.getY()));
        Board.spaces.add( new Space("Balamb",jButton_Yellow1.getX(),jButton_Yellow1.getY()));
        Board.spaces.add( new Space("Esthar",jButton_Yellow2.getX(),jButton_Yellow2.getY()));
        Board.spaces.add( new Space("Water Works",jButton_Utility_Water.getX(),jButton_Utility_Water.getY()));
        Board.spaces.add( new Space("Lunatic Pandora",jButton_Yellow3.getX(),jButton_Yellow3.getY()));
        Board.spaces.add( new Space("Go to Jail",jButton_GoToJail.getX(),jButton_GoToJail.getY()));
        Board.spaces.add( new Space("Alexandria",jButton_Green1.getX(),jButton_Green1.getY()));
        Board.spaces.add( new Space("Burmecia",jButton_Green2.getX(),jButton_Green2.getY()));
        Board.spaces.add( new Space("Community Chest",jButton_Chest3.getX(),jButton_Chest3.getY()));
        Board.spaces.add( new Space("Ban Bal",jButton_Green3.getX(),jButton_Green3.getY()));
        Board.spaces.add( new Space("*Rail4*",jButton_Rail4.getX(),jButton_Rail4.getY()));
        Board.spaces.add( new Space("Chance",jButton_Chance3.getX(),jButton_Chance3.getY()));
        Board.spaces.add( new Space("Besaid",jButton_Blue1.getX(),jButton_Blue1.getY()));
        Board.spaces.add( new Space("Luxury Tax",jButton_Tax_Lux.getX(),jButton_Tax_Lux.getY()));
        Board.spaces.add( new Space("Zanarkand",jButton_Blue2.getX(),jButton_Blue2.getY()));
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel_Player1 = new javax.swing.JLabel();
        jButton_Rail1 = new javax.swing.JButton();
        jButton_Rail2 = new javax.swing.JButton();
        jButton_Rail3 = new javax.swing.JButton();
        jButton_Rail4 = new javax.swing.JButton();
        jButton_Utility_Electric = new javax.swing.JButton();
        jButton_Utility_Water = new javax.swing.JButton();
        jButton_Go = new javax.swing.JButton();
        jButton_FreeParking = new javax.swing.JButton();
        jButton_Jail = new javax.swing.JButton();
        jButton_GoToJail = new javax.swing.JButton();
        jButton_Tax_Income = new javax.swing.JButton();
        jButton_Tax_Lux = new javax.swing.JButton();
        jButton_Chest1 = new javax.swing.JButton();
        jButton_Chest2 = new javax.swing.JButton();
        jButton_Chest3 = new javax.swing.JButton();
        jButton_Chance1 = new javax.swing.JButton();
        jButton_Chance2 = new javax.swing.JButton();
        jButton_Chance3 = new javax.swing.JButton();
        jButton_Purple1 = new javax.swing.JButton();
        jButton_Purple2 = new javax.swing.JButton();
        jButton_Teal1 = new javax.swing.JButton();
        jButton_Teal2 = new javax.swing.JButton();
        jButton_Teal3 = new javax.swing.JButton();
        jButton_Pink1 = new javax.swing.JButton();
        jButton_Pink2 = new javax.swing.JButton();
        jButton_Pink3 = new javax.swing.JButton();
        jButton_Orange1 = new javax.swing.JButton();
        jButton_Orange2 = new javax.swing.JButton();
        jButton_Orange3 = new javax.swing.JButton();
        jButton_Red1 = new javax.swing.JButton();
        jButton_Red2 = new javax.swing.JButton();
        jButton_Red3 = new javax.swing.JButton();
        jButton_Yellow1 = new javax.swing.JButton();
        jButton_Yellow2 = new javax.swing.JButton();
        jButton_Yellow3 = new javax.swing.JButton();
        jButton_Green1 = new javax.swing.JButton();
        jButton_Green2 = new javax.swing.JButton();
        jButton_Green3 = new javax.swing.JButton();
        jButton_Blue1 = new javax.swing.JButton();
        jButton_Blue2 = new javax.swing.JButton();
        Center = new javax.swing.JLabel();
        jPanel_Player1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Money = new javax.swing.JTextField();
        jTextField_Location = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel_Player3 = new javax.swing.JPanel();
        jTextField_Money1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Player7 = new javax.swing.JPanel();
        jTextField_Money6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel_Player5 = new javax.swing.JPanel();
        jTextField_Money4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel_Player8 = new javax.swing.JPanel();
        jTextField_Money7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel_Player6 = new javax.swing.JPanel();
        jTextField_Money5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel_Player4 = new javax.swing.JPanel();
        jTextField_Money3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel_Player2 = new javax.swing.JPanel();
        jTextField_Money2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_Exit = new javax.swing.JMenuItem();
        jMenu_Game = new javax.swing.JMenu();
        jMenuItem_AddPlayer = new javax.swing.JMenuItem();
        jMenu_Player = new javax.swing.JMenu();
        jMenuItem_Move = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 768));
        setUndecorated(true);

        jLabel_Player1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Car.png"))); // NOI18N
        jLabel_Player1.setBounds(640, 670, 53, 33);
        jLayeredPane1.add(jLabel_Player1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Rail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Rail.png"))); // NOI18N
        jButton_Rail1.setAlignmentY(0.0F);
        jButton_Rail1.setBorderPainted(false);
        jButton_Rail1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Rail1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Rail1.setOpaque(false);
        jButton_Rail1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Rail1.setBounds(330, 630, 60, 90);
        jLayeredPane1.add(jButton_Rail1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Rail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/RailL.png"))); // NOI18N
        jButton_Rail2.setAlignmentY(0.0F);
        jButton_Rail2.setBorderPainted(false);
        jButton_Rail2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Rail2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Rail2.setOpaque(false);
        jButton_Rail2.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Rail2.setBounds(0, 330, 90, 60);
        jLayeredPane1.add(jButton_Rail2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Rail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Rail.png"))); // NOI18N
        jButton_Rail3.setAlignmentY(0.0F);
        jButton_Rail3.setBorderPainted(false);
        jButton_Rail3.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Rail3.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Rail3.setOpaque(false);
        jButton_Rail3.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Rail3.setBounds(330, 0, 60, 90);
        jLayeredPane1.add(jButton_Rail3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Rail4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/RailR.png"))); // NOI18N
        jButton_Rail4.setAlignmentY(0.0F);
        jButton_Rail4.setBorderPainted(false);
        jButton_Rail4.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Rail4.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Rail4.setOpaque(false);
        jButton_Rail4.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Rail4.setBounds(630, 330, 90, 60);
        jLayeredPane1.add(jButton_Rail4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Utility_Electric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Utility_E.png"))); // NOI18N
        jButton_Utility_Electric.setAlignmentY(0.0F);
        jButton_Utility_Electric.setBorderPainted(false);
        jButton_Utility_Electric.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Utility_Electric.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Utility_Electric.setOpaque(false);
        jButton_Utility_Electric.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Utility_Electric.setBounds(0, 510, 90, 60);
        jLayeredPane1.add(jButton_Utility_Electric, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Utility_Water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Utility_W.png"))); // NOI18N
        jButton_Utility_Water.setAlignmentY(0.0F);
        jButton_Utility_Water.setBorderPainted(false);
        jButton_Utility_Water.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Utility_Water.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Utility_Water.setOpaque(false);
        jButton_Utility_Water.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Utility_Water.setBounds(510, 0, 60, 90);
        jLayeredPane1.add(jButton_Utility_Water, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/cornergo.png"))); // NOI18N
        jButton_Go.setAlignmentY(0.0F);
        jButton_Go.setBorderPainted(false);
        jButton_Go.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_Go.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_Go.setOpaque(false);
        jButton_Go.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_Go.setBounds(630, 630, 90, 90);
        jLayeredPane1.add(jButton_Go, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_FreeParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/cornerfreepark.png"))); // NOI18N
        jButton_FreeParking.setAlignmentY(0.0F);
        jButton_FreeParking.setBorderPainted(false);
        jButton_FreeParking.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_FreeParking.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_FreeParking.setOpaque(false);
        jButton_FreeParking.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_FreeParking.setBounds(0, 0, 90, 90);
        jLayeredPane1.add(jButton_FreeParking, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Jail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/cornerinjail.png"))); // NOI18N
        jButton_Jail.setAlignmentY(0.0F);
        jButton_Jail.setBorderPainted(false);
        jButton_Jail.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_Jail.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_Jail.setOpaque(false);
        jButton_Jail.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_Jail.setBounds(0, 630, 90, 90);
        jLayeredPane1.add(jButton_Jail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_GoToJail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/cornerjail.png"))); // NOI18N
        jButton_GoToJail.setAlignmentY(0.0F);
        jButton_GoToJail.setBorderPainted(false);
        jButton_GoToJail.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_GoToJail.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_GoToJail.setOpaque(false);
        jButton_GoToJail.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_GoToJail.setBounds(630, 0, 90, 90);
        jLayeredPane1.add(jButton_GoToJail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Tax_Income.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Tax_In.png"))); // NOI18N
        jButton_Tax_Income.setAlignmentY(0.0F);
        jButton_Tax_Income.setBorderPainted(false);
        jButton_Tax_Income.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Tax_Income.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Tax_Income.setOpaque(false);
        jButton_Tax_Income.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Tax_Income.setBounds(390, 630, 60, 90);
        jLayeredPane1.add(jButton_Tax_Income, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Tax_Lux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Tax_Lux.png"))); // NOI18N
        jButton_Tax_Lux.setAlignmentY(0.0F);
        jButton_Tax_Lux.setBorderPainted(false);
        jButton_Tax_Lux.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Tax_Lux.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Tax_Lux.setOpaque(false);
        jButton_Tax_Lux.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Tax_Lux.setBounds(630, 510, 90, 60);
        jLayeredPane1.add(jButton_Tax_Lux, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Chest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Chest.png"))); // NOI18N
        jButton_Chest1.setAlignmentY(0.0F);
        jButton_Chest1.setBorderPainted(false);
        jButton_Chest1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Chest1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Chest1.setOpaque(false);
        jButton_Chest1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Chest1.setBounds(510, 630, 60, 90);
        jLayeredPane1.add(jButton_Chest1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Chest2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/ChestL.png"))); // NOI18N
        jButton_Chest2.setAlignmentY(0.0F);
        jButton_Chest2.setBorderPainted(false);
        jButton_Chest2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Chest2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Chest2.setOpaque(false);
        jButton_Chest2.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Chest2.setBounds(0, 210, 90, 60);
        jLayeredPane1.add(jButton_Chest2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Chest3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/ChestR.png"))); // NOI18N
        jButton_Chest3.setAlignmentY(0.0F);
        jButton_Chest3.setBorderPainted(false);
        jButton_Chest3.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Chest3.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Chest3.setOpaque(false);
        jButton_Chest3.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Chest3.setBounds(630, 210, 90, 60);
        jLayeredPane1.add(jButton_Chest3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Chance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Chance.png"))); // NOI18N
        jButton_Chance1.setAlignmentY(0.0F);
        jButton_Chance1.setBorderPainted(false);
        jButton_Chance1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Chance1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Chance1.setOpaque(false);
        jButton_Chance1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Chance1.setBounds(210, 630, 60, 90);
        jLayeredPane1.add(jButton_Chance1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Chance2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Chance.png"))); // NOI18N
        jButton_Chance2.setAlignmentY(0.0F);
        jButton_Chance2.setBorderPainted(false);
        jButton_Chance2.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Chance2.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Chance2.setOpaque(false);
        jButton_Chance2.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Chance2.setBounds(150, 0, 60, 90);
        jLayeredPane1.add(jButton_Chance2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Chance3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/ChanceR.png"))); // NOI18N
        jButton_Chance3.setAlignmentY(0.0F);
        jButton_Chance3.setBorderPainted(false);
        jButton_Chance3.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Chance3.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Chance3.setOpaque(false);
        jButton_Chance3.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Chance3.setBounds(630, 390, 90, 60);
        jLayeredPane1.add(jButton_Chance3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Purple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Purple1_FF.png"))); // NOI18N
        jButton_Purple1.setAlignmentY(0.0F);
        jButton_Purple1.setBorderPainted(false);
        jButton_Purple1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Purple1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Purple1.setOpaque(false);
        jButton_Purple1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Purple1.setBounds(570, 630, 60, 90);
        jLayeredPane1.add(jButton_Purple1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Purple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Purple2_Pan.png"))); // NOI18N
        jButton_Purple2.setAlignmentY(0.0F);
        jButton_Purple2.setBorderPainted(false);
        jButton_Purple2.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Purple2.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Purple2.setOpaque(false);
        jButton_Purple2.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Purple2.setBounds(450, 630, 60, 90);
        jLayeredPane1.add(jButton_Purple2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Teal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Teal1_floating.png"))); // NOI18N
        jButton_Teal1.setAlignmentY(0.0F);
        jButton_Teal1.setBorderPainted(false);
        jButton_Teal1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Teal1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Teal1.setOpaque(false);
        jButton_Teal1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Teal1.setBounds(270, 630, 60, 90);
        jLayeredPane1.add(jButton_Teal1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Teal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Teal2_Crystal.png"))); // NOI18N
        jButton_Teal2.setAlignmentY(0.0F);
        jButton_Teal2.setBorderPainted(false);
        jButton_Teal2.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Teal2.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Teal2.setOpaque(false);
        jButton_Teal2.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Teal2.setBounds(150, 630, 60, 90);
        jLayeredPane1.add(jButton_Teal2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Teal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Teal3_Baron.png"))); // NOI18N
        jButton_Teal3.setAlignmentY(0.0F);
        jButton_Teal3.setBorderPainted(false);
        jButton_Teal3.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Teal3.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Teal3.setOpaque(false);
        jButton_Teal3.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Teal3.setBounds(90, 630, 60, 90);
        jLayeredPane1.add(jButton_Teal3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Pink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Pink1_Library.png"))); // NOI18N
        jButton_Pink1.setAlignmentY(0.0F);
        jButton_Pink1.setBorderPainted(false);
        jButton_Pink1.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Pink1.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Pink1.setOpaque(false);
        jButton_Pink1.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Pink1.setBounds(0, 570, 90, 60);
        jLayeredPane1.add(jButton_Pink1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Pink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Pink2_Exdeath.png"))); // NOI18N
        jButton_Pink2.setAlignmentY(0.0F);
        jButton_Pink2.setBorderPainted(false);
        jButton_Pink2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Pink2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Pink2.setOpaque(false);
        jButton_Pink2.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Pink2.setBounds(0, 450, 90, 60);
        jLayeredPane1.add(jButton_Pink2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Pink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Pink3_Kuza.png"))); // NOI18N
        jButton_Pink3.setAlignmentY(0.0F);
        jButton_Pink3.setBorderPainted(false);
        jButton_Pink3.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Pink3.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Pink3.setOpaque(false);
        jButton_Pink3.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Pink3.setBounds(0, 390, 90, 60);
        jLayeredPane1.add(jButton_Pink3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Orange1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Orange1_Figaro.png"))); // NOI18N
        jButton_Orange1.setAlignmentY(0.0F);
        jButton_Orange1.setBorderPainted(false);
        jButton_Orange1.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Orange1.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Orange1.setOpaque(false);
        jButton_Orange1.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Orange1.setBounds(0, 270, 90, 60);
        jLayeredPane1.add(jButton_Orange1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Orange2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Orange2_Imperial.png"))); // NOI18N
        jButton_Orange2.setAlignmentY(0.0F);
        jButton_Orange2.setBorderPainted(false);
        jButton_Orange2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Orange2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Orange2.setOpaque(false);
        jButton_Orange2.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Orange2.setBounds(0, 150, 90, 60);
        jLayeredPane1.add(jButton_Orange2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Orange3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Orange3_Kefka.png"))); // NOI18N
        jButton_Orange3.setAlignmentY(0.0F);
        jButton_Orange3.setBorderPainted(false);
        jButton_Orange3.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Orange3.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Orange3.setOpaque(false);
        jButton_Orange3.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Orange3.setBounds(0, 90, 90, 60);
        jLayeredPane1.add(jButton_Orange3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Red1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Red1_Saucer.png"))); // NOI18N
        jButton_Red1.setAlignmentY(0.0F);
        jButton_Red1.setBorderPainted(false);
        jButton_Red1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Red1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Red1.setOpaque(false);
        jButton_Red1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Red1.setBounds(90, 0, 60, 90);
        jLayeredPane1.add(jButton_Red1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Red2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Red2_Junon.png"))); // NOI18N
        jButton_Red2.setAlignmentY(0.0F);
        jButton_Red2.setBorderPainted(false);
        jButton_Red2.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Red2.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Red2.setOpaque(false);
        jButton_Red2.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Red2.setBounds(210, 0, 60, 90);
        jLayeredPane1.add(jButton_Red2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Red3_Midgar.png"))); // NOI18N
        jButton_Red3.setAlignmentY(0.0F);
        jButton_Red3.setBorderPainted(false);
        jButton_Red3.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Red3.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Red3.setOpaque(false);
        jButton_Red3.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Red3.setBounds(270, 0, 60, 90);
        jLayeredPane1.add(jButton_Red3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Yellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Yellow1_Balamb.png"))); // NOI18N
        jButton_Yellow1.setAlignmentY(0.0F);
        jButton_Yellow1.setBorderPainted(false);
        jButton_Yellow1.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Yellow1.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Yellow1.setOpaque(false);
        jButton_Yellow1.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Yellow1.setBounds(390, 0, 60, 90);
        jLayeredPane1.add(jButton_Yellow1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Yellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Yellow2_Esthar.png"))); // NOI18N
        jButton_Yellow2.setAlignmentY(0.0F);
        jButton_Yellow2.setBorderPainted(false);
        jButton_Yellow2.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Yellow2.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Yellow2.setOpaque(false);
        jButton_Yellow2.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Yellow2.setBounds(450, 0, 60, 90);
        jLayeredPane1.add(jButton_Yellow2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Yellow3_Lunatic.png"))); // NOI18N
        jButton_Yellow3.setAlignmentY(0.0F);
        jButton_Yellow3.setBorderPainted(false);
        jButton_Yellow3.setMaximumSize(new java.awt.Dimension(60, 90));
        jButton_Yellow3.setMinimumSize(new java.awt.Dimension(60, 90));
        jButton_Yellow3.setOpaque(false);
        jButton_Yellow3.setPreferredSize(new java.awt.Dimension(60, 90));
        jButton_Yellow3.setBounds(570, 0, 60, 90);
        jLayeredPane1.add(jButton_Yellow3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Green1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Green1_Alexandria.png"))); // NOI18N
        jButton_Green1.setAlignmentY(0.0F);
        jButton_Green1.setBorderPainted(false);
        jButton_Green1.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Green1.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Green1.setOpaque(false);
        jButton_Green1.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Green1.setBounds(630, 90, 90, 60);
        jLayeredPane1.add(jButton_Green1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Green2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Green2_Burmecia.png"))); // NOI18N
        jButton_Green2.setAlignmentY(0.0F);
        jButton_Green2.setBorderPainted(false);
        jButton_Green2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Green2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Green2.setOpaque(false);
        jButton_Green2.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Green2.setBounds(630, 150, 90, 60);
        jLayeredPane1.add(jButton_Green2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Green3_BanBal.png"))); // NOI18N
        jButton_Green3.setAlignmentY(0.0F);
        jButton_Green3.setBorderPainted(false);
        jButton_Green3.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Green3.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Green3.setOpaque(false);
        jButton_Green3.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Green3.setBounds(630, 270, 90, 60);
        jLayeredPane1.add(jButton_Green3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Blue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Blue1_Besaid.png"))); // NOI18N
        jButton_Blue1.setAlignmentY(0.0F);
        jButton_Blue1.setBorderPainted(false);
        jButton_Blue1.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Blue1.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Blue1.setOpaque(false);
        jButton_Blue1.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Blue1.setBounds(630, 450, 90, 60);
        jLayeredPane1.add(jButton_Blue1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton_Blue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/Blue2_Zanarkand.png"))); // NOI18N
        jButton_Blue2.setAlignmentY(0.0F);
        jButton_Blue2.setBorderPainted(false);
        jButton_Blue2.setMaximumSize(new java.awt.Dimension(100, 67));
        jButton_Blue2.setMinimumSize(new java.awt.Dimension(100, 67));
        jButton_Blue2.setOpaque(false);
        jButton_Blue2.setPreferredSize(new java.awt.Dimension(100, 67));
        jButton_Blue2.setBounds(630, 570, 90, 60);
        jLayeredPane1.add(jButton_Blue2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Center.setIcon(new javax.swing.ImageIcon(getClass().getResource("/board_Resources/real1.png"))); // NOI18N
        Center.setBounds(90, 90, 540, 540);
        jLayeredPane1.add(Center, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel_Player1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Player 1"));

        jLabel1.setText("Funds:");

        jTextField_Money.setEditable(false);

        jTextField_Location.setEditable(false);

        jLabel9.setText("Location:");

        javax.swing.GroupLayout jPanel_Player1Layout = new javax.swing.GroupLayout(jPanel_Player1);
        jPanel_Player1.setLayout(jPanel_Player1Layout);
        jPanel_Player1Layout.setHorizontalGroup(
            jPanel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player1Layout.createSequentialGroup()
                .addGroup(jPanel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_Player1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_Player1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel_Player1Layout.setVerticalGroup(
            jPanel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player1Layout.createSequentialGroup()
                .addGroup(jPanel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_Money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        jPanel_Player3.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 3"));

        jTextField_Money1.setEditable(false);

        jLabel2.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player3Layout = new javax.swing.GroupLayout(jPanel_Player3);
        jPanel_Player3.setLayout(jPanel_Player3Layout);
        jPanel_Player3Layout.setHorizontalGroup(
            jPanel_Player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel_Player3Layout.setVerticalGroup(
            jPanel_Player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player3Layout.createSequentialGroup()
                .addGroup(jPanel_Player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_Money1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
        );

        jPanel_Player7.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 7"));

        jTextField_Money6.setEditable(false);

        jLabel7.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player7Layout = new javax.swing.GroupLayout(jPanel_Player7);
        jPanel_Player7.setLayout(jPanel_Player7Layout);
        jPanel_Player7Layout.setHorizontalGroup(
            jPanel_Player7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel_Player7Layout.setVerticalGroup(
            jPanel_Player7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player7Layout.createSequentialGroup()
                .addGroup(jPanel_Player7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_Money6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
        );

        jPanel_Player5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Player 5"));

        jTextField_Money4.setEditable(false);

        jLabel5.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player5Layout = new javax.swing.GroupLayout(jPanel_Player5);
        jPanel_Player5.setLayout(jPanel_Player5Layout);
        jPanel_Player5Layout.setHorizontalGroup(
            jPanel_Player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel_Player5Layout.setVerticalGroup(
            jPanel_Player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player5Layout.createSequentialGroup()
                .addGroup(jPanel_Player5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Money4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 109, Short.MAX_VALUE))
        );

        jPanel_Player8.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 8"));

        jTextField_Money7.setEditable(false);

        jLabel8.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player8Layout = new javax.swing.GroupLayout(jPanel_Player8);
        jPanel_Player8.setLayout(jPanel_Player8Layout);
        jPanel_Player8Layout.setHorizontalGroup(
            jPanel_Player8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player8Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel_Player8Layout.setVerticalGroup(
            jPanel_Player8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player8Layout.createSequentialGroup()
                .addGroup(jPanel_Player8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_Money7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
        );

        jPanel_Player6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Player 6"));

        jTextField_Money5.setEditable(false);

        jLabel6.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player6Layout = new javax.swing.GroupLayout(jPanel_Player6);
        jPanel_Player6.setLayout(jPanel_Player6Layout);
        jPanel_Player6Layout.setHorizontalGroup(
            jPanel_Player6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player6Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel_Player6Layout.setVerticalGroup(
            jPanel_Player6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player6Layout.createSequentialGroup()
                .addGroup(jPanel_Player6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Money5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 109, Short.MAX_VALUE))
        );

        jPanel_Player4.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 4"));

        jTextField_Money3.setEditable(false);

        jLabel4.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player4Layout = new javax.swing.GroupLayout(jPanel_Player4);
        jPanel_Player4.setLayout(jPanel_Player4Layout);
        jPanel_Player4Layout.setHorizontalGroup(
            jPanel_Player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel_Player4Layout.setVerticalGroup(
            jPanel_Player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player4Layout.createSequentialGroup()
                .addGroup(jPanel_Player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Money3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
        );

        jPanel_Player2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Player 2"));

        jTextField_Money2.setEditable(false);

        jLabel3.setText("Funds:");

        javax.swing.GroupLayout jPanel_Player2Layout = new javax.swing.GroupLayout(jPanel_Player2);
        jPanel_Player2.setLayout(jPanel_Player2Layout);
        jPanel_Player2Layout.setHorizontalGroup(
            jPanel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Money2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel_Player2Layout.setVerticalGroup(
            jPanel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Player2Layout.createSequentialGroup()
                .addGroup(jPanel_Player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Money2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 109, Short.MAX_VALUE))
        );

        jMenu_File.setText("File");

        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_ExitMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem_ExitMousePressed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu_File);

        jMenu_Game.setText("Game");
        jMenu_Game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu_GameMousePressed(evt);
            }
        });

        jMenuItem_AddPlayer.setText("Add Player");
        jMenuItem_AddPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_AddPlayerMouseClicked(evt);
            }
        });
        jMenu_Game.add(jMenuItem_AddPlayer);

        jMenuBar1.add(jMenu_Game);

        jMenu_Player.setText("Player");

        jMenuItem_Move.setText("Move");
        jMenuItem_Move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem_MoveMousePressed(evt);
            }
        });
        jMenu_Player.add(jMenuItem_Move);

        jMenuBar1.add(jMenu_Player);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Player1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_Player2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Player4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel_Player6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Player8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLayeredPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Player2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Player3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Player5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Player7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Player8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_AddPlayerMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuItem_AddPlayerMouseClicked
    {//GEN-HEADEREND:event_jMenuItem_AddPlayerMouseClicked
        
    }//GEN-LAST:event_jMenuItem_AddPlayerMouseClicked

    private void jMenuItem_ExitMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuItem_ExitMouseClicked
    {//GEN-HEADEREND:event_jMenuItem_ExitMouseClicked
        
    }//GEN-LAST:event_jMenuItem_ExitMouseClicked

    private void jMenuItem_ExitMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuItem_ExitMousePressed
    {//GEN-HEADEREND:event_jMenuItem_ExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_ExitMousePressed

    private void jMenuItem_MoveMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenuItem_MoveMousePressed
    {//GEN-HEADEREND:event_jMenuItem_MoveMousePressed
        int dist = Game.players.get(Game.currentPlayer).roll();
        Game.players.get(Game.currentPlayer).Move( dist );
        jTextField_Location.setText(Board.spaces.get(Game.players.get(Game.currentPlayer).location).Name);
        jLabel_Player1.setLocation(Board.spaces.get(Game.players.get(Game.currentPlayer).location).XPos,
                Board.spaces.get(Game.players.get(Game.currentPlayer).location).YPos);
    }//GEN-LAST:event_jMenuItem_MoveMousePressed

    private void jMenu_GameMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu_GameMousePressed
    {//GEN-HEADEREND:event_jMenu_GameMousePressed
        Game.addPlayer();
        jLabel_Player1.setLocation(Board.spaces.get(Game.players.get(Game.currentPlayer).location).XPos,
                Board.spaces.get(Game.players.get(Game.currentPlayer).location).YPos);
    }//GEN-LAST:event_jMenu_GameMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Center;
    private javax.swing.JButton jButton_Blue1;
    private javax.swing.JButton jButton_Blue2;
    private javax.swing.JButton jButton_Chance1;
    private javax.swing.JButton jButton_Chance2;
    private javax.swing.JButton jButton_Chance3;
    private javax.swing.JButton jButton_Chest1;
    private javax.swing.JButton jButton_Chest2;
    private javax.swing.JButton jButton_Chest3;
    private javax.swing.JButton jButton_FreeParking;
    private javax.swing.JButton jButton_Go;
    private javax.swing.JButton jButton_GoToJail;
    private javax.swing.JButton jButton_Green1;
    private javax.swing.JButton jButton_Green2;
    private javax.swing.JButton jButton_Green3;
    private javax.swing.JButton jButton_Jail;
    private javax.swing.JButton jButton_Orange1;
    private javax.swing.JButton jButton_Orange2;
    private javax.swing.JButton jButton_Orange3;
    private javax.swing.JButton jButton_Pink1;
    private javax.swing.JButton jButton_Pink2;
    private javax.swing.JButton jButton_Pink3;
    private javax.swing.JButton jButton_Purple1;
    private javax.swing.JButton jButton_Purple2;
    private javax.swing.JButton jButton_Rail1;
    private javax.swing.JButton jButton_Rail2;
    private javax.swing.JButton jButton_Rail3;
    private javax.swing.JButton jButton_Rail4;
    private javax.swing.JButton jButton_Red1;
    private javax.swing.JButton jButton_Red2;
    private javax.swing.JButton jButton_Red3;
    private javax.swing.JButton jButton_Tax_Income;
    private javax.swing.JButton jButton_Tax_Lux;
    private javax.swing.JButton jButton_Teal1;
    private javax.swing.JButton jButton_Teal2;
    private javax.swing.JButton jButton_Teal3;
    private javax.swing.JButton jButton_Utility_Electric;
    private javax.swing.JButton jButton_Utility_Water;
    private javax.swing.JButton jButton_Yellow1;
    private javax.swing.JButton jButton_Yellow2;
    private javax.swing.JButton jButton_Yellow3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Player1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_AddPlayer;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_Move;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Game;
    private javax.swing.JMenu jMenu_Player;
    private javax.swing.JPanel jPanel_Player1;
    private javax.swing.JPanel jPanel_Player2;
    private javax.swing.JPanel jPanel_Player3;
    private javax.swing.JPanel jPanel_Player4;
    private javax.swing.JPanel jPanel_Player5;
    private javax.swing.JPanel jPanel_Player6;
    private javax.swing.JPanel jPanel_Player7;
    private javax.swing.JPanel jPanel_Player8;
    private javax.swing.JTextField jTextField_Location;
    private javax.swing.JTextField jTextField_Money;
    private javax.swing.JTextField jTextField_Money1;
    private javax.swing.JTextField jTextField_Money2;
    private javax.swing.JTextField jTextField_Money3;
    private javax.swing.JTextField jTextField_Money4;
    private javax.swing.JTextField jTextField_Money5;
    private javax.swing.JTextField jTextField_Money6;
    private javax.swing.JTextField jTextField_Money7;
    // End of variables declaration//GEN-END:variables
}
